LankaBookin/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LankaBookin.Models
{
    [Table("Lb_Apartment")]
    public class Apartment:BaseModel
    {
        public Apartment()
        {
            this.ApartmentImages = new HashSet<ApartmentImage>();
            this.RoomsBook = new HashSet<RoomsBook>();
            this.Rating = new HashSet<Rating>();
            this.UserWishList = new HashSet<UserWishList>();
            this.BookingRequest = new HashSet<BookingRequest>();
            this.Facilities = new HashSet<Facility>();
            this.Accomadations = new HashSet<AccomadationType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Star { get; set; }
        public decimal Rate { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Description { get; set; }
        public bool IsPerRoom { get; set; }
        public int RoomCount { get; set; }
        public decimal Price { get; set; }
        public int MaxHeadCount { get; set; }
        public int UserId { get; set; }
        public int CityId { get; set; }
        public Nullable<int> LandmarkId { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual Landmark Landmark { get; set; }
        public virtual ICollection<ApartmentImage> ApartmentImages { get; set; }
        public virtual ICollection<RoomsBook> RoomsBook { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual ICollection<UserWishList> UserWishList { get; set; }
        public virtual ICollection<BookingRequest> BookingRequest { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
        public virtual ICollection<AccomadationType> Accomadations { get; set; }
    }
}

LankaBookin/Controllers/ApartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LankaBookin.Models;
using LankaBookin.DAL;
using WebMatrix.WebData;
using System.IO;

namespace LankaBookin.Controllers
{
    [Authorize]
    public class ApartmentController : Controller
    {
        private LankaBookinEntities db = new LankaBookinEntities();

        //
        // GET: /Apartment/
        [Authorize]
        [Authorize(Roles = "Internal")]
        public ActionResult Index()
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);
            return View(db.Apartment.Where(a => a.UserId == userId && a.Deleted != true).ToList());
        }

        [Authorize]
        public ActionResult ApartmentList(DateTime? checkin = null, DateTime? checkout = null,int desId=0)
        {
            ViewBag.DesId = desId;
            return PartialView(db.Apartment.Where(a => a.Deleted != true).ToList());
        }

        //
        // GET: /Apartment/
        [AllowAnonymous]
        public ActionResult Search(string search = "", DateTime? checkin = null, DateTime? checkout = null, int AccomadationTypes = 0)
        {
            List<Apartment> apartments;
            List<Apartment> apartmentList;

            if (!string.IsNullOrEmpty(search))
            {
                apartments = db.Apartment.Where(a => a.Deleted != true && a.Name.Contains(search)).ToList();
                apartmentList = db.Apartment.Where(a => a.Deleted != true && a.Name.Contains(search)).ToList();
            }
            else
            {
                apartments = db.Apartment.Where(a => a.Deleted != true).ToList();
                apartmentList = db.Apartment.Where(a => a.Deleted != true).ToList();
            }

            foreach (var apartment in apartments)
            {
                if (checkin != null && checkout != null)
                {
                    DateTime date=(DateTime)checkin;
                    while(date<=checkout)
                    {
                        var result = db.RoomsBook.Where(r => r.ApartmentId == apartment.Id && r.Date == date).Select(r=>r.RoomCount).Count();
                        if (result > 0)
                        {
                            if (!apartment.IsPerRoom)
                            {
                                apartmentList.Remove(apartment);
                            }
                            else
                            {
                                if (apartment.RoomCount <= result)
                                {
                                    apartmentList.Remove(apartment);
                                }
                            }
                        }

                        date = date.AddDays(1);
                    }

                }
            }

            ViewBag.AccomadationTypes = new SelectList(db.AccomadationType, "Id", "AccomadationName");
            ViewBag.CityId = new SelectList(db.City, "Id", "CityName");
            List<Facility> facilities = db.Facility.ToList();
            ViewBag.Facilities = facilities;

            return View(apartmentList);
        }

        [AllowAnonymous]
        public ActionResult DetailsPartial(int id = 0)
        {
            Apartment lb_apartment = db.Apartment.Find(id);
            if (lb_apartment == null)
            {
                return HttpNotFound();
            }

            return PartialView(lb_apartment); ;
        }

        //
        // GET: /Apartment/Details/5
        public ActionResult Details(int id = 0)
        {
            Apartment lb_apartment = db.Apartment.Find(id);
            if (lb_apartment == null)
            {
                return HttpNotFound();
            }
            return View(lb_apartment);
        }

        //
        // GET: /Apartment/Details/5
        [Authorize(Roles = "Internal")]
        public ActionResult InternalDetails(int id = 0)
        {
            Apartment lb_apartment = db.Apartment.Find(id);
            if (lb_apartment == null)
            {
                return HttpNotFound();
            }
            return View(lb_apartment);
        }

        //
        // GET: /Apartment/Create
        [Authorize(Roles = "Internal")]
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.City, "Id", "CityName");
            List<AccomadationType> accomadationTypes = db.AccomadationType.ToList();
            ViewBag.AccomadationTypes = accomadationTypes;
            List<Facility> facilities = db.Facility.ToList();
            ViewBag.Facilities = facilities;
            return View();
        }

        //
        // POST: /Apartment/Create

        [HttpPost]
        [Authorize(Roles = "Internal")]
        public ActionResult Create(Apartment apartment, HttpPostedFileBase[] files)
        {
            if (files.Count() > 15)
            {
                ModelState.AddModelError("upload", "Maxmimum upload count is 15 images");
            }

            if (ModelState.IsValid)
            {
                int userId = WebSecurity.GetUserId(User.Identity.Name);

                if (apartment.UserId == 0)
                {
                    apartment.UserId = userId;
                }

                apartment.Deleted = false;
                apartment.CreatedDate = DateTime.Now;
                apartment.CreatedBy = userId;
                db.Apartment.Add(apartment);
                db.SaveChanges();

                List<AccomadationType> accomadationTypes = db.AccomadationType.ToList();
                foreach (AccomadationType type in accomadationTypes)
                {
                    var result = Request[Convert.ToString("Acc"+type.Id)];
                    if (result != null)
                    {
                        if (result.ToString() == "on")
                        {
                            apartment.Accomadations.Add(type);
                            db.SaveChanges();
                        }
                    }

                }

                List<Facility> facilities = db.Facility.ToList();
                foreach (Facility type in facilities)
                {
                    var result = Request[Convert.ToString("Fac" + type.Id)];
                    if (result != null)
                    {
                        if (result.ToString() == "on")
                        {
                            apartment.Facilities.Add(type);
                            db.SaveChanges();
                        }
                    }

                }

                foreach (HttpPostedFileBase file in files)
                {
                    if (file != null)
                    {
                        string pic = System.IO.Path.GetFileName(file.FileName);
                        string path = Server.MapPath("~/Images/Apartment/"+apartment.Name);
                        string fullPath = System.IO.Path.Combine(path, pic);

                        if (!Directory.Exists(path))
                        {
                            DirectoryInfo di = Directory.CreateDirectory(path);
                        }

                        // file is uploaded
                        file.SaveAs(fullPath);

                    }
                }

                return RedirectToAction("Index");
            }

            ViewBag.CityId = new SelectList(db.City, "Id", "CityName", apartment.CityId);
            List<AccomadationType> accomadationType = db.AccomadationType.ToList();
            ViewBag.AccomadationTypes = accomadationType; 
            List<Facility> facility = db.Facility.ToList();
            ViewBag.Facilities = facility;
            return View(apartment);
        }

        //
        // GET: /Apartment/Edit/5
        [Authorize(Roles = "Internal")]
        public ActionResult Edit(int id = 0)
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);
            Apartment apartment = db.Apartment.Where(a => a.Id == id && a.UserId == userId).SingleOrDefault();
            
            if (apartment == null)
            {
                return HttpNotFound();
            }

            ViewBag.CityId = new SelectList(db.City, "Id", "CityName", apartment.CityId);

            List<AccomadationType> accomadationType = db.AccomadationType.ToList();
            ViewBag.AccomadationTypes = accomadationType;

            List<Facility> facility = db.Facility.ToList();
            ViewBag.Facilities = facility;
            return View(apartment);
        }

        //
        // POST: /Apartment/Edit/5

        [HttpPost]
        [Authorize(Roles = "Internal")]
        public ActionResult Edit(Apartment apartment, HttpPostedFileBase[] files, string[] selectedAccomadationTypes, string[] selectedFacilities)
        {
            string fpath = Server.MapPath("~/Images/Apartment/" + apartment.Name);
            int fCount = Directory.GetFiles(fpath, "*", SearchOption.AllDirectories).Length;

            if (files.Count() + fCount > 15)
            {
                ModelState.AddModelError("upload", "Maxmimum upload count is 15 images");
            }

            if (ModelState.IsValid)
            {
                apartment.ModifiedDate = DateTime.Now;
                db.Entry(apartment).State = EntityState.Modified;
                db.SaveChanges();

                ICollection<AccomadationType> accomadationTypes = new HashSet<AccomadationType>();
                if (selectedAccomadationTypes != null)
                {
                    foreach (var accomadationType in db.AccomadationType.ToList())
                    {
                        if (selectedAccomadationTypes.ToList().Contains(accomadationType.Id.ToString()))
                        {
                            accomadationType.Apartments.Add(apartment);
                            accomadationTypes.Add(accomadationType);

LankaBookin/Views/Apartment/ApartmentList.cshtml
@model IEnumerable<LankaBookin.Models.Apartment>

        <script type="text/javascript">
            $(function () {
                $('.modal').click(function () {
                    $('#divInDialog').dialog({
                        close: function (event, ui) {
                            dialog.remove();
                        },
                        modal: true
                    }).load(this.href, {});

                    return false;
                });

                $('.selectAprt').click(function (e) {
                    var desId = '@ViewBag.DesId';
                    var ids = e.target.id;
                    var id = ids.substring(5);
                    $('#sa'+desId).val(id);
                    $.getJSON("/Apartment/GetApartmentName", { apartmentId: id },
                  function (data, status) {
                      $('#aprt_name' + desId).val(data.name);
                      if (data.isPerRoom) {
                          $('#price_des' + desId).text('Price per room');
                      }
                      else {
                          $('#price_des' + desId).text('Price per whole apartment');
                      }
                      $('#price' + desId).val(data.price);
                      $('#d' + desId).show();
                      $('#window').hide();
                  });
                });

            });
        </script>

@{       
   var grid = new WebGrid(source: Model,
                defaultSort: "Name",
                rowsPerPage: 20);
}

<div id="grid">
    @grid.GetHtml(
        tableStyle: "grid table table-striped table-bordered",
        headerStyle: "head",
        alternatingRowStyle: "alt",
        columns: grid.Columns(
            grid.Column("Name"),
            grid.Column("Star"),
            grid.Column("Rate"),
            grid.Column("Address1"),
            grid.Column("Address2"),
            grid.Column("Description"),
            grid.Column(header:"IsPerRoom?", format:@<text><input type="checkbox" checked="@item.IsPerRoom" disabled="disabled" /></text>),
            grid.Column("RoomCount"),
            grid.Column("MaxHeadCount"),
            grid.Column(header:"City", format:@<text><div>@(item.City.CityName)</div></text>),
            grid.Column(header: "", format: item => new HtmlString(Html.ActionLink("Details", "DetailsPartial", new { id = item.Id }, new { @class = "modal" } ).ToString())),
            grid.Column(header:"", format:@<text><label class="selectAprt" id="saprt@(item.Id)"> Select apartment</label></text>)
        )
    )
</div>

<div id="divInDialog">

</div>

LankaBookin/Views/Apartment/Create.cshtml
@model LankaBookin.Models.Apartment

@{
    ViewBag.Title = "Apartment Create";
    Layout = "~/Views/Shared/_UserProfileLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Apartment", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Lb_Apartment</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Star)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Star)
            @Html.ValidationMessageFor(model => model.Star)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsPerRoom)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsPerRoom)
            @Html.ValidationMessageFor(model => model.IsPerRoom)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address1)
            @Html.ValidationMessageFor(model => model.Address1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address2)
            @Html.ValidationMessageFor(model => model.Address2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoomCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoomCount)
            @Html.ValidationMessageFor(model => model.RoomCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaxHeadCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaxHeadCount)
            @Html.ValidationMessageFor(model => model.MaxHeadCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityId, "City")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityId", String.Empty)
            @Html.ValidationMessageFor(model => model.CityId)
        </div>

        <div>
            <label>Select Accomadation Type </label>
            @foreach (var item in ViewBag.AccomadationTypes)
            {
                <input type="checkbox" id="Acc@(item.Id)" name="Acc@(item.Id)" />
                @item.AccomadationName 
            }

        </div>

        <div>
            <label>Select Apartment Facilities </label>
            @foreach (var item in ViewBag.Facilities)
            {
                <input type="checkbox" id="Fac@(item.Id)" name="Fac@(item.Id)" />
                @item.FacilityName 
            }

        </div>

        <label for="file">Upload Images:(Maxmimum 15 images)</label> 
        <input type="file" multiple="multiple" name="files" id="files" style="width: 30%;" /> 
        @Html.ValidationMessage("upload")

        <p>
            <input id="save" type="submit" value="Create" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

</script>


<div class="btn btn-default b-l">
    @Html.ActionLink("Back to List", "Index")
</div>

LankaBookin/Views/Apartment/Delete.cshtml
@model LankaBookin.Models.Apartment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_UserProfileLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Apartment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Star)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Star)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsPerRoom)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsPerRoom)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RoomCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoomCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MaxHeadCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaxHeadCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CityId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CityId)
    </div>
    
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> 
        <div class="btn btn-default b-l">
            @Html.ActionLink("Back to List", "Index")
            </div>
</p>
}

LankaBookin/Views/Apartment/DetailsPartial.cshtml
@model LankaBookin.Models.Apartment

<fieldset>
    <legend>Apartment</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Star)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Star)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsPerRoom)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsPerRoom)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RoomCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RoomCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MaxHeadCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MaxHeadCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City.CityName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City.CityName)
    </div>
    
</fieldset>

LankaBookin/Views/Apartment/Edit.cshtml
@model LankaBookin.Models.Apartment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_UserProfileLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Apartment", FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Apartment</legend>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.Deleted)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.CreatedDate)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Star)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Star)
            @Html.ValidationMessageFor(model => model.Star)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rate)
            @Html.ValidationMessageFor(model => model.Rate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address1)
            @Html.ValidationMessageFor(model => model.Address1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address2)
            @Html.ValidationMessageFor(model => model.Address2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsPerRoom)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsPerRoom)
            @Html.ValidationMessageFor(model => model.IsPerRoom)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RoomCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RoomCount)
            @Html.ValidationMessageFor(model => model.RoomCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaxHeadCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaxHeadCount)
            @Html.ValidationMessageFor(model => model.MaxHeadCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CityId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CityId)
            @Html.ValidationMessageFor(model => model.CityId)
        </div>

        <div>
            <label>Select Accomadation Type </label>
            @foreach (var accomadationType in ViewBag.AccomadationTypes)
            {
                <input type="checkbox" name="selectedAccomadationTypes" id="Acc@(accomadationType.Id)" value="@(accomadationType.Id)" @(Html.Raw(accomadationType.Apartments.Contains(Model) ? "checked=\"checked\"" : "")) />
                @accomadationType.AccomadationName 
            }

        </div>

        <div>
            <label>Select Apartment Facilities </label>
            @foreach (var facility in ViewBag.Facilities)
            {
                <div>
                <input type="checkbox" name="selectedFacilities" id="Fac@(facility.Id)" value="@(facility.Id)"  @(Html.Raw(facility.Apartments.Contains(Model) ? "checked=\"checked\"" : "")) />
                @facility.FacilityName 
                    </div>
            }

        </div>

        <label for="file">Upload Images:(Maxmimum 15 images)</label> 
        <input type="file" multiple="multiple" name="files" id="files" style="width: 30%;" /> 
        @Html.ValidationMessage("upload")

        @{
            int counter = 1;
        }

        @foreach (var imgPath in Directory.GetFiles(Server.MapPath("~/Images/Apartment/" + Model.Name), "*.jpg"))
        {
            var img = new FileInfo(imgPath);
            <img class="img" src="@Url.Content(String.Format("~/Images/Apartment/{0}/{1}",Model.Name, img.Name))" id="img@(counter)" width="100" height="100" />
            counter++;
        }

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div class="btn btn-default b-l">
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $(function () {
        $('.img').click(function (event) {
            if (confirm('Are you sure you want to delete this image')) {
                var item = $(event.target).attr('src')
                var id = event.target.id;
                $.getJSON("/Apartment/DeleteImage", { imagePath: item },
                  function (data, status) {
                      $('#' + id).hide();
                  }
                );
            }
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LankaBookin/Views/Apartment/Index.cshtml
@model IEnumerable<LankaBookin.Models.Apartment>
@using GridMvc.Html

@{
    ViewBag.Title = "Apartment List";
    Layout = "~/Views/Shared/_UserProfileLayout.cshtml";
}

<h2>Index</h2>

<div class="clear-fix">&nbsp;</div>
<p class="btn btn-primary btn-success link-c-n">
    <span class="glyphicon glyphicon-plus"></span>
    @Html.ActionLink("Create New", "Create")
</p>

@Html.Grid(Model).Columns(columns =>
          {
              columns.Add(t => t.Name).Titled("Apartment Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.Rate).Titled("Rating").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.City.CityName).Titled("City").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("VIEW", "InternalDetails", "Apartment", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());
              columns.Add().Titled("Actions").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("EDIT", "Edit", "Apartment", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-success" }).ToHtmlString());
              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("DELETE", "Delete", "Apartment", new { id = o.Id, page = ViewBag.Page }, new { @class = "btn btn-danger modal-link" }).ToHtmlString());

          }).WithPaging(1)

    
              